#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

if [ ! -f settings ]; then
  echo "Error loading configuration; settings file missing."
  exit 1
fi

source ./settings

curl -o etcd-v2.0.13-linux-amd64.tar.gz -L https://github.com/coreos/etcd/releases/download/v2.0.13/etcd-v2.0.13-linux-amd64.tar.gz
tar -xvf etcd-v2.0.13-linux-amd64.tar.gz
cp etcd-v2.0.13-linux-amd64/etcd etcd-v2.0.13-linux-amd64/etcdctl etcd/
pushd etcd
docker build -t kuar.io/etcd:2.0.13 .
popd
rm -rf etcd-v2.0.13-linux-amd64*
rm etcd/etcd etcd/etcdctl

for b in kube-apiserver kube-proxy kube-scheduler kube-controller-manager kubelet kubectl; do
  curl -o ${b}/${b} -L ${KUBERNETES_RELEASE_URL}/${b}
  chmod +x ${b}/${b}
  pushd ${b}/
  docker build -t kuar.io/${b}:${KUBERNETES_VERSION} .
  rm ${b}
  popd
done
