#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

if [ ! -f settings ]; then
  echo "Error loading configuration; settings file missing."
  exit 1
fi

source ./settings

for b in kube-apiserver kube-proxy kube-scheduler kube-controller-manager kubelet kubectl; do
  curl -o ${b}/${b} -L ${KUBERNETES_RELEASE_URL}/${b}
  chmod +x ${b}/${b}
  pushd ${b}/
  docker build -t ${b}:${KUBERNETES_VERSION} .
  rm ${b}
  popd
done
